param(
    [string]$Stage = "sandbox",
    [string]$Unit = "draft_canvas_cinder_930296"
)

Write-Host "Executing synthetic task for $Unit at stage $Stage"
$root = "https://demo.orbitlane.local"
Write-Host "Root endpoint: $root"

Write-Host "Synthetic step 1 done"
Write-Host "Synthetic step 2 done"
Write-Host "Synthetic step 3 done"
Write-Host "Synthetic step 4 done"
Write-Host "Synthetic step 5 done"
Write-Host "Synthetic step 6 done"
Write-Host "Synthetic step 7 done"
Write-Host "Synthetic step 8 done"
Write-Host "Synthetic step 9 done"
Write-Host "Synthetic step 10 done"
Write-Host "Synthetic step 11 done"
Write-Host "Synthetic step 12 done"
Write-Host "Synthetic step 13 done"
Write-Host "Synthetic step 14 done"
Write-Host "Synthetic step 15 done"
Write-Host "Synthetic step 16 done"
Write-Host "Synthetic step 17 done"
Write-Host "Synthetic step 18 done"
Write-Host "Synthetic step 19 done"
Write-Host "Synthetic step 20 done"
Write-Host "Synthetic step 21 done"
Write-Host "Synthetic step 22 done"
Write-Host "Synthetic step 23 done"