param(
    [string]$Stage = "sandbox",
    [string]$Unit = "parcel_delta_ripple_74e250"
)

Write-Host "Executing synthetic task for $Unit at stage $Stage"
$root = "https://demo.orbitlane.local"
Write-Host "Root endpoint: $root"

Write-Host "Synthetic step 1 done"
Write-Host "Synthetic step 2 done"
Write-Host "Synthetic step 3 done"
Write-Host "Synthetic step 4 done"
Write-Host "Synthetic step 5 done"
Write-Host "Synthetic step 6 done"
Write-Host "Synthetic step 7 done"
Write-Host "Synthetic step 8 done"
Write-Host "Synthetic step 9 done"
Write-Host "Synthetic step 10 done"
Write-Host "Synthetic step 11 done"
Write-Host "Synthetic step 12 done"
Write-Host "Synthetic step 13 done"
Write-Host "Synthetic step 14 done"
Write-Host "Synthetic step 15 done"
Write-Host "Synthetic step 16 done"
Write-Host "Synthetic step 17 done"
Write-Host "Synthetic step 18 done"
Write-Host "Synthetic step 19 done"
Write-Host "Synthetic step 20 done"
Write-Host "Synthetic step 21 done"
Write-Host "Synthetic step 22 done"
Write-Host "Synthetic step 23 done"
Write-Host "Synthetic step 24 done"
Write-Host "Synthetic step 25 done"
Write-Host "Synthetic step 26 done"
Write-Host "Synthetic step 27 done"
Write-Host "Synthetic step 28 done"
Write-Host "Synthetic step 29 done"
Write-Host "Synthetic step 30 done"
Write-Host "Synthetic step 31 done"
Write-Host "Synthetic step 32 done"
Write-Host "Synthetic step 33 done"
Write-Host "Synthetic step 34 done"
Write-Host "Synthetic step 35 done"
Write-Host "Synthetic step 36 done"
Write-Host "Synthetic step 37 done"
Write-Host "Synthetic step 38 done"
Write-Host "Synthetic step 39 done"
Write-Host "Synthetic step 40 done"
Write-Host "Synthetic step 41 done"
Write-Host "Synthetic step 42 done"
Write-Host "Synthetic step 43 done"
Write-Host "Synthetic step 44 done"
Write-Host "Synthetic step 45 done"
Write-Host "Synthetic step 46 done"
Write-Host "Synthetic step 47 done"
Write-Host "Synthetic step 48 done"
Write-Host "Synthetic step 49 done"
Write-Host "Synthetic step 50 done"
Write-Host "Synthetic step 51 done"
Write-Host "Synthetic step 52 done"
Write-Host "Synthetic step 53 done"
Write-Host "Synthetic step 54 do